apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-config-writer
rules:
  - apiGroups:
      - imageregistry.operator.openshift.io
    resources:
      - configs
    verbs:
      - get
      - list
      - watch
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: registry-config-writer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-config-writer
subjects:
  - kind: ServiceAccount
    name: registry-sa
    namespace: module1
