apiVersion: "v1"
kind: PersistentVolumeClaim
metadata: 
  name: image-registry-storage
  namespace: openshift-image-registry
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: ocs-external-storagecluster-cephfs
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests: 
      storage: "500Gi"
