apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: module1
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    name: ""
    namespace: module1
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  source:
    repoURL: 'https://github.com/learn-quarkus/quarkus-beginners-helm.git'
    targetRevision: 'main'
    path: module1
    helm:
      valuesObject:
      